# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='books.Comment'),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='books.Rating'),
        ),
    ]
